name: ci

env:
  AWS_API_KEY: "${{ secrets.AWS_API_KEY }}"

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
  
jobs:
  build:
    if: contains(toJson(github.event.commits), '[ci skip]') == false
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v5

    - uses: mlugg/setup-zig@2.0.5

    - name: Debug
      run: zig build run -Dbuild-example

    - name: Release
      run: zig build run -Dbuild-example -Doptimize=ReleaseSafe
